[package]
name = "cve-score"
version = "0.0.1"
authors = ["Lukas Pustina <lukas@pustina.de>"]
edition = "2018"

[dependencies]
cvss = "1"
reqwest = { version = "0.10", default-features = false, features = ["rustls-tls", "json", "trust-dns"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tabwriter = "1.2"
thiserror = "1"
tokio = { version = "0.2", features = ["full"] }
