[package]
name = "cve-scorer"
version = "1.0.0"
authors = ["Lukas Pustina <lukas@pustina.de>"]
edition = "2018"
description = "Retrieve and compare CVSS scores of CVEs"
repository = "https://github.com/lukaspustina/cve-scrorer.git"
readme = "README.md"
license = "MIT"
keywords = ["security", "CVE", "CVSS", "cli"]
include = [
    "README.md",
    "LICENSE",
    "CHANGELOG.md",
    "**/*.rs",
    "Cargo.toml",
]

[[bin]]
name = "cve-scorer"
path = "src/bin/cve-scorer.rs"

[lib]
name = "cvescorer"
path = "src/lib.rs"

[dependencies]
cvss = "1"
futures = { version = "0.3.*"}
reqwest = { version = "0.10", default-features = false, features = ["rustls-tls", "json", "trust-dns"] }
serde = { version = "1", features = ["derive"] }
structopt = { version = "0.3" }
tabwriter = "1.2"
thiserror = "1"
tokio = { version = "0.2", features = ["full"] }

[dev-dependencies]
lit = "1"
serde_json = "1"
spectral = "0.6"
